version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: savoon-bank-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET:-your_secure_jwt_secret_here}
      - JWT_EXPIRE=${JWT_EXPIRE:-24h}
      - SIGNUP_CREDIT_AMOUNT=${SIGNUP_CREDIT_AMOUNT:-1000}
      - DATABASE_PATH=/app/database/finance.sqlite
    volumes:
      # Persist database data
      - backend_data:/app/database
      # Persist logs
      - backend_logs:/app/logs
    networks:
      - savoon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: savoon-bank-frontend
    ports:
      - "3000:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - savoon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  savoon-network:
    driver: bridge
    name: savoon-network

volumes:
  backend_data:
    name: savoon-bank-backend-data
  backend_logs:
    name: savoon-bank-backend-logs
