// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Transaction Types
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_TRANSACTIONS = 'CLEAR_TRANSACTIONS';

// Analytics Types
export const GET_ANALYTICS_DATA = 'GET_ANALYTICS_DATA';
export const ANALYTICS_ERROR = 'ANALYTICS_ERROR';
export const SET_ANALYTICS_LOADING = 'SET_ANALYTICS_LOADING';
export const SET_DATE_RANGE = 'SET_DATE_RANGE';
export const CLEAR_ANALYTICS = 'CLEAR_ANALYTICS';
