apiVersion: apps/v1
kind: Deployment
metadata:
  name: savoon-bank-frontend
  labels:
    app: savoon-bank-frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: savoon-bank-frontend
  template:
    metadata:
      labels:
        app: savoon-bank-frontend
        tier: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: frontend
        image: ghcr.io/your-org/savoon-bank/frontend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: savoon-bank-frontend-service
  labels:
    app: savoon-bank-frontend
spec:
  selector:
    app: savoon-bank-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
