#!/bin/bash

echo "🛡️ Savoon Bank Security Scanning Guide"
echo "======================================"
echo ""
echo "📋 Available Scripts:"
echo "  ./scripts/security-scan.sh [service] [severity]"
echo "    - Quick security scan (production deps only)"
echo "    - Example: ./scripts/security-scan.sh backend high"
echo ""
echo "  ./scripts/test-dependencies.sh [service]"
echo "    - Comprehensive dependency analysis"
echo "    - Example: ./scripts/test-dependencies.sh frontend"
echo ""
echo "🔧 Manual Commands:"
echo "  cd backend && npm audit --omit=dev"
echo "    - Quick npm audit (production only)"
echo ""
echo "  cd backend && snyk test --prod"
echo "    - Snyk scan (production only)"
echo ""
echo "  cd backend && npm ci --omit=dev"
echo "    - Install production dependencies only"
echo ""
echo "📊 Why Production Dependencies Only?"
echo "  ✓ Focus on code that reaches production"
echo "  ✓ Faster scans and fewer false positives"
echo "  ✓ Better security prioritization"
echo "  ✓ Compliance with security standards"
echo ""
echo "🚀 Setup Requirements:"
echo "  - npm install -g snyk (for local Snyk CLI)"
echo "  - snyk auth (authenticate with Snyk)"
echo "  - Set SNYK_TOKEN environment variable for CI/CD"
